### PR TITLE
Improve decode performance

### PR DESCRIPTION
**Pull request by codesoap**
This change reduces the amount of calculations with `*big.Int` (`result.Mul` and `result.Add`) in `Decode` by transforming most of the calculations to simple `int64` ones. This improves performance by something between 200% and 500% on my (amd64) laptop, according to the provided benchmarks.

The inner loop goes through a maximum of 10 iterations, since `var m int64` can only hold `58**10`, but not `58**11`.

The change makes the code harder to read, but since you said in the README you're interested in performance improvements, I'll propose it anyway. I'll let you decide whether you prefer performance or readability.

### CODE REVIEW

**Comment by akamensky** [comment]
Can you please add in the comments the benchmark comparison of current master and your change?

The code looks fine (and passes tests), but it the Github Actions benchmark shows lower numbers than the current master branch.

**Comment by codesoap** [comment]
Hm, that's interesting. What is the architecture of the GitHub Actions benchmark? I could imagine, that my change doesn't perform as well on 32bit machines, since it uses `int64`...

Without my change (current master):
```
$ go test -bench='Decode*'
goos: openbsd
goarch: amd64
pkg: github.com/akamensky/base58
cpu: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
BenchmarkDecode32-2       421952              2750 ns/op          11.64 MB/s
BenchmarkDecode64-2       211719              5574 ns/op          11.48 MB/s
BenchmarkDecode128-2       99670             12245 ns/op          10.45 MB/s
BenchmarkDecode256-2       38865             29905 ns/op           8.56 MB/s
BenchmarkDecode512-2       18048             70169 ns/op           7.30 MB/s
PASS
ok      github.com/akamensky/base58     33.534s
```

With my change:
```
$ go test -bench='Decode*'
goos: openbsd
goarch: amd64
pkg: github.com/akamensky/base58
cpu: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
BenchmarkDecode32-2      1529082               776.7 ns/op        41.20 MB/s
BenchmarkDecode64-2       929634              1374 ns/op          46.57 MB/s
BenchmarkDecode128-2      449370              2635 ns/op          48.58 MB/s
BenchmarkDecode256-2      217635              5847 ns/op          43.79 MB/s
BenchmarkDecode512-2       98802             12753 ns/op          40.15 MB/s
PASS
ok      github.com/akamensky/base58     120.751s
```

**Comment by akamensky** [comment]
Sorry, my bad, I was looking at Encode benchmark results, not Decode, not sure why they are different by ~10%. Could be different host with some additional load, or slower memory.

Not sure if the "checks" tab is visible to you here, the results from Github Actions are:

```
goos: linux
goarch: amd64
pkg: github.com/akamensky/base58
cpu: Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
BenchmarkEncode32-2    	  281442	      4293 ns/op	   7.45 MB/s
BenchmarkEncode64-2    	  100798	     11140 ns/op	   5.75 MB/s
BenchmarkEncode128-2   	   39648	     29457 ns/op	   4.35 MB/s
BenchmarkEncode256-2   	   12741	     93650 ns/op	   2.73 MB/s
BenchmarkEncode512-2   	    3985	    324960 ns/op	   1.58 MB/s
BenchmarkDecode32-2    	 1791676	       674.4 ns/op	  47.45 MB/s
BenchmarkDecode64-2    	  966186	      1327 ns/op	  48.24 MB/s
BenchmarkDecode128-2   	  477118	      2584 ns/op	  49.54 MB/s
BenchmarkDecode256-2   	  223012	      5389 ns/op	  47.51 MB/s
BenchmarkDecode512-2   	  100052	     12001 ns/op	  42.66 MB/s
PASS
```

Yesterday merge (current master tip):

```
 goos: linux
goarch: amd64
pkg: github.com/akamensky/base58
cpu: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
BenchmarkEncode32-2    	  330958	      3548 ns/op	   9.02 MB/s
BenchmarkEncode64-2    	  137366	      9031 ns/op	   7.09 MB/s
BenchmarkEncode128-2   	   47568	     23909 ns/op	   5.35 MB/s
BenchmarkEncode256-2   	   16416	     74359 ns/op	   3.44 MB/s
BenchmarkEncode512-2   	    4789	    249208 ns/op	   2.05 MB/s
BenchmarkDecode32-2    	  576888	      1922 ns/op	  16.65 MB/s
BenchmarkDecode64-2    	  282474	      4173 ns/op	  15.34 MB/s
BenchmarkDecode128-2   	  136521	      9551 ns/op	  13.40 MB/s
BenchmarkDecode256-2   	   50234	     23449 ns/op	  10.92 MB/s
BenchmarkDecode512-2   	   20923	     61718 ns/op	   8.30 MB/s
PASS
```

**Comment by codesoap** [comment]
I learned from @mvdan about https://github.com/aclements/perflock. I'm not exactly sure what the tool does, but it somehow makes performance benchmarks less noisy, which helps when comparing performances. I did not use it here either, though...

I'm not sure, however, if it can be enabled for the GitHub Action...

**Pull request merged**
